name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            docker build . --file dockerfile -t mahmom/jenkins_iti:v1.10
            docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker push mahmom/jenkins_iti:v1.10
